trigger:
  batch: true
  branches:
    include:
    - main

pool: 
  vmImage: ubuntu-latest

variables:
  - group: 'AVD'

stages:
  - template: pipeline/infrastructure/build-avd-infrastructure.yml 

  - template: pipeline/infrastructure/deploy-avd-infrastructure.yml
    parameters:
      VariableGroup: 'AVD'
      AzureResourceManagerConnection: $(AzureResourceManagerConnection)
      Environment: 'test'
      SubscriptionId: $(SubscriptionId.Test)

  - template: pipeline/infrastructure/deploy-avd-infrastructure.yml 
    parameters:
      VariableGroup: 'AVD'
      AzureResourceManagerConnection: $(AzureResourceManagerConnection)
      Environment: 'prod' 
      SubscriptionId: $(SubscriptionId.Prod)
