parameters:
- name: AzureResourceManagerConnection
  type: string
- name: SubscriptionId
  type: string
- name: Location
  type: string
  default: 'West Europe'
- name: Environment
  type: string
- name: VariableGroup
  type: string
  
stages:
- stage: deployment_${{ parameters.Environment }}
  displayName: Deployment ${{ parameters.Environment }}
  variables:
  - group: ${{ parameters.VariableGroup }}
  jobs: 
    - deployment: deployment_${{ parameters.Environment }}
      displayName: Deployment ${{ parameters.Environment }}
      environment: '${{ parameters.Environment }}'
      strategy: 
        runOnce:
          deploy:
            steps:
              - download: current

              - template: ../templates/steps/set.subscriptionId.yml
                parameters:
                  AzureResourceManagerConnection: ${{ parameters.AzureResourceManagerConnection }}
                  SubscriptionId: ${{ parameters.SubscriptionId }}

              - template: steps/deploy.infrastructure.arms.yml
                parameters:
                  AzureResourceManagerConnection: ${{ parameters.AzureResourceManagerConnection }}
                  SubscriptionId: $(Set.SubscriptionId)
                  Location: ${{ parameters.Location }}
                  Environment: ${{ parameters.Environment }}
                  DeploymentMode: Incremental